name: Compile and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    permissions:
      # Needed to create releases
      contents: write

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      
    - name: Build
      run: dotnet publish ViciousGPT\ViciousGPT.csproj /p:PublishProfile=ViciousGPT\Properties\PublishProfiles\FolderProfile.pubxml
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Release artifact
        path: ViciousGPT\bin\Release\net8.0-windows\publish\win-x64\ViciousGPT.exe
      
    - name: Remove latest release
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 0
        delete_tag_pattern: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update latest tag
      uses: richardsimko/update-tag@v1
      with:
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        prerelease: true
        name: Latest Build
        generate_release_notes: true
        files: ViciousGPT/bin/Release/net8.0-windows/publish/win-x64/ViciousGPT.exe
    
